apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: evers419/kwetter:gateway-service-latest
          ports:
            - containerPort: 8080
            - containerPort: 50055

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  template:
    metadata:
      labels:
        app: accountservice
    spec:
      containers:
        - name: accountservice
          image: evers419/kwetter:account-service-latest
          ports:
            - containerPort: 50054

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      containers:
        - name: authservice
          image: evers419/kwetter:auth-service-latest
          ports:
            - containerPort: 50053

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: trendservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trendservice
  template:
    metadata:
      labels:
        app: trendservice
    spec:
      containers:
        - name: trendservice
          image: evers419/kwetter:trend-service-latest
          ports:
            - containerPort: 50052

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweetservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweetservice
  template:
    metadata:
      labels:
        app: tweetservice
    spec:
      containers:
        - name: tweetservice
          image: evers419/kwetter:tweet-service-latest
          ports:
            - containerPort: 50051