apiVersion: v1
kind: Service
metadata:
  name: gatewayservice
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50055
      targetPort: 50055
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: accountservice
spec:
  selector:
    app: accountservice
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054

---

apiVersion: v1
kind: Service
metadata:
  name: authservice
spec:
  selector:
    app: authservice
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053

---

apiVersion: v1
kind: Service
metadata:
  name: trendservice
spec:
  selector:
    app: trendservice
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052

---

apiVersion: v1
kind: Service
metadata:
  name: tweetservice
spec:
  selector:
    app: tweetservice
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051