apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: grpc
      protocol: TCP
      port: 50055
      targetPort: 50055
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: account-service
spec:
  selector:
    app: account-service
  ports:
    - protocol: TCP
      port: 50054
      targetPort: 50054

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 50053
      targetPort: 50053

---

apiVersion: v1
kind: Service
metadata:
  name: trend-service
spec:
  selector:
    app: trend-service
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052

---

apiVersion: v1
kind: Service
metadata:
  name: tweet-service
spec:
  selector:
    app: tweet-service
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051