// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.0
// source: tweet.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TweetService_ReturnAll_FullMethodName   = "/proto.TweetService/ReturnAll"
	TweetService_ReturnTweet_FullMethodName = "/proto.TweetService/ReturnTweet"
	TweetService_PostTweet_FullMethodName   = "/proto.TweetService/PostTweet"
)

// TweetServiceClient is the client API for TweetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TweetServiceClient interface {
	ReturnAll(ctx context.Context, in *ReturnAllReq, opts ...grpc.CallOption) (*ReturnAllRes, error)
	ReturnTweet(ctx context.Context, in *ReturnTweetReq, opts ...grpc.CallOption) (*ReturnTweetRes, error)
	PostTweet(ctx context.Context, in *PostTweetReq, opts ...grpc.CallOption) (*PostTweetRes, error)
}

type tweetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTweetServiceClient(cc grpc.ClientConnInterface) TweetServiceClient {
	return &tweetServiceClient{cc}
}

func (c *tweetServiceClient) ReturnAll(ctx context.Context, in *ReturnAllReq, opts ...grpc.CallOption) (*ReturnAllRes, error) {
	out := new(ReturnAllRes)
	err := c.cc.Invoke(ctx, TweetService_ReturnAll_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetServiceClient) ReturnTweet(ctx context.Context, in *ReturnTweetReq, opts ...grpc.CallOption) (*ReturnTweetRes, error) {
	out := new(ReturnTweetRes)
	err := c.cc.Invoke(ctx, TweetService_ReturnTweet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetServiceClient) PostTweet(ctx context.Context, in *PostTweetReq, opts ...grpc.CallOption) (*PostTweetRes, error) {
	out := new(PostTweetRes)
	err := c.cc.Invoke(ctx, TweetService_PostTweet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TweetServiceServer is the server API for TweetService service.
// All implementations must embed UnimplementedTweetServiceServer
// for forward compatibility
type TweetServiceServer interface {
	ReturnAll(context.Context, *ReturnAllReq) (*ReturnAllRes, error)
	ReturnTweet(context.Context, *ReturnTweetReq) (*ReturnTweetRes, error)
	PostTweet(context.Context, *PostTweetReq) (*PostTweetRes, error)
	mustEmbedUnimplementedTweetServiceServer()
}

// UnimplementedTweetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTweetServiceServer struct {
}

func (UnimplementedTweetServiceServer) ReturnAll(context.Context, *ReturnAllReq) (*ReturnAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnAll not implemented")
}
func (UnimplementedTweetServiceServer) ReturnTweet(context.Context, *ReturnTweetReq) (*ReturnTweetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnTweet not implemented")
}
func (UnimplementedTweetServiceServer) PostTweet(context.Context, *PostTweetReq) (*PostTweetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTweet not implemented")
}
func (UnimplementedTweetServiceServer) mustEmbedUnimplementedTweetServiceServer() {}

// UnsafeTweetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TweetServiceServer will
// result in compilation errors.
type UnsafeTweetServiceServer interface {
	mustEmbedUnimplementedTweetServiceServer()
}

func RegisterTweetServiceServer(s grpc.ServiceRegistrar, srv TweetServiceServer) {
	s.RegisterService(&TweetService_ServiceDesc, srv)
}

func _TweetService_ReturnAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).ReturnAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TweetService_ReturnAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).ReturnAll(ctx, req.(*ReturnAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TweetService_ReturnTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnTweetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).ReturnTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TweetService_ReturnTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).ReturnTweet(ctx, req.(*ReturnTweetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TweetService_PostTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTweetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).PostTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TweetService_PostTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).PostTweet(ctx, req.(*PostTweetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TweetService_ServiceDesc is the grpc.ServiceDesc for TweetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TweetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TweetService",
	HandlerType: (*TweetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReturnAll",
			Handler:    _TweetService_ReturnAll_Handler,
		},
		{
			MethodName: "ReturnTweet",
			Handler:    _TweetService_ReturnTweet_Handler,
		},
		{
			MethodName: "PostTweet",
			Handler:    _TweetService_PostTweet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tweet.proto",
}
