// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: gateway.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TweetService_ReturnAll_FullMethodName   = "/proto.TweetService/ReturnAll"
	TweetService_ReturnTweet_FullMethodName = "/proto.TweetService/ReturnTweet"
	TweetService_PostTweet_FullMethodName   = "/proto.TweetService/postTweet"
)

// TweetServiceClient is the client API for TweetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TweetServiceClient interface {
	ReturnAll(ctx context.Context, in *ReturnAllReq, opts ...grpc.CallOption) (TweetService_ReturnAllClient, error)
	ReturnTweet(ctx context.Context, in *ReturnTweetReq, opts ...grpc.CallOption) (*ReturnTweetRes, error)
	PostTweet(ctx context.Context, in *PostTweetReq, opts ...grpc.CallOption) (*PostTweetRes, error)
}

type tweetServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTweetServiceClient(cc grpc.ClientConnInterface) TweetServiceClient {
	return &tweetServiceClient{cc}
}

func (c *tweetServiceClient) ReturnAll(ctx context.Context, in *ReturnAllReq, opts ...grpc.CallOption) (TweetService_ReturnAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &TweetService_ServiceDesc.Streams[0], TweetService_ReturnAll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &tweetServiceReturnAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TweetService_ReturnAllClient interface {
	Recv() (*ReturnAllRes, error)
	grpc.ClientStream
}

type tweetServiceReturnAllClient struct {
	grpc.ClientStream
}

func (x *tweetServiceReturnAllClient) Recv() (*ReturnAllRes, error) {
	m := new(ReturnAllRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tweetServiceClient) ReturnTweet(ctx context.Context, in *ReturnTweetReq, opts ...grpc.CallOption) (*ReturnTweetRes, error) {
	out := new(ReturnTweetRes)
	err := c.cc.Invoke(ctx, TweetService_ReturnTweet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tweetServiceClient) PostTweet(ctx context.Context, in *PostTweetReq, opts ...grpc.CallOption) (*PostTweetRes, error) {
	out := new(PostTweetRes)
	err := c.cc.Invoke(ctx, TweetService_PostTweet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TweetServiceServer is the server API for TweetService service.
// All implementations must embed UnimplementedTweetServiceServer
// for forward compatibility
type TweetServiceServer interface {
	ReturnAll(*ReturnAllReq, TweetService_ReturnAllServer) error
	ReturnTweet(context.Context, *ReturnTweetReq) (*ReturnTweetRes, error)
	PostTweet(context.Context, *PostTweetReq) (*PostTweetRes, error)
	mustEmbedUnimplementedTweetServiceServer()
}

// UnimplementedTweetServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTweetServiceServer struct {
}

func (UnimplementedTweetServiceServer) ReturnAll(*ReturnAllReq, TweetService_ReturnAllServer) error {
	return status.Errorf(codes.Unimplemented, "method ReturnAll not implemented")
}
func (UnimplementedTweetServiceServer) ReturnTweet(context.Context, *ReturnTweetReq) (*ReturnTweetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReturnTweet not implemented")
}
func (UnimplementedTweetServiceServer) PostTweet(context.Context, *PostTweetReq) (*PostTweetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostTweet not implemented")
}
func (UnimplementedTweetServiceServer) mustEmbedUnimplementedTweetServiceServer() {}

// UnsafeTweetServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TweetServiceServer will
// result in compilation errors.
type UnsafeTweetServiceServer interface {
	mustEmbedUnimplementedTweetServiceServer()
}

func RegisterTweetServiceServer(s grpc.ServiceRegistrar, srv TweetServiceServer) {
	s.RegisterService(&TweetService_ServiceDesc, srv)
}

func _TweetService_ReturnAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReturnAllReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TweetServiceServer).ReturnAll(m, &tweetServiceReturnAllServer{stream})
}

type TweetService_ReturnAllServer interface {
	Send(*ReturnAllRes) error
	grpc.ServerStream
}

type tweetServiceReturnAllServer struct {
	grpc.ServerStream
}

func (x *tweetServiceReturnAllServer) Send(m *ReturnAllRes) error {
	return x.ServerStream.SendMsg(m)
}

func _TweetService_ReturnTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnTweetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).ReturnTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TweetService_ReturnTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).ReturnTweet(ctx, req.(*ReturnTweetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _TweetService_PostTweet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostTweetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TweetServiceServer).PostTweet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TweetService_PostTweet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TweetServiceServer).PostTweet(ctx, req.(*PostTweetReq))
	}
	return interceptor(ctx, in, info, handler)
}

// TweetService_ServiceDesc is the grpc.ServiceDesc for TweetService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TweetService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.TweetService",
	HandlerType: (*TweetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReturnTweet",
			Handler:    _TweetService_ReturnTweet_Handler,
		},
		{
			MethodName: "postTweet",
			Handler:    _TweetService_PostTweet_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReturnAll",
			Handler:       _TweetService_ReturnAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gateway.proto",
}
