apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AuthService
  template:
    metadata:
      labels:
        app: AuthService
    spec:
      containers:
        - name: AuthService
          image: evers419/kwetter-auth-service:latest
          ports:
            - containerPort: 50053