name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  ACTIONS_STEP_DEBUG: true
  DOCKER_USERNAME:  ${{ secrets.DOCKER_USERNAME }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
  tweet-service:
    environment: TweetService
    name: Build TweetService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go env
        uses: actions/setup-go@v3
        with: 
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build Tweet Service
        working-directory: TweetService
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kwetter:tweet-service .
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: TweetService
          file: TweetService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:tweet-service
