name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

        
  tweet-service:
    environment: TweetService
    name: Build TweetService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go and secrets
        uses: actions/setup-go@v3
        with: 
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          
      - name: Build
        run: |
          cd TweetService
          docker build -t kwetter/tweet-service -f Dockerfile.md .
          
      - name: Deploy tweet service
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          repository: ${{ secrets.DOCKER_USERNAME }}/kwetter
          tags: latest
          
