name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tweet-service:
    environment: TweetService
    name: Build TweetService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go env
        uses: actions/setup-go@v3
        with: 
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          
      - name: Build Tweet Service
        working-directory: ./TweetService
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kwetter:tweet-service .
      
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./TweetService
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:tweet-service
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
