name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  ACTIONS_STEP_DEBUG: true

jobs:
  tweet-service:
    environment: TweetService
    name: Build TweetService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go env
        uses: actions/setup-go@v3
        with: 
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
 
      - name: Check for changes in TweetService
        id: check-tweet-service
        run: |
          git fetch
          changed_files=$(git diff --name-only origin/main -- TweetService/)
          echo "::set-output name=changes::${changed_files}"
      
      - name: Build Tweet Service
        if: ${{ steps.check-tweet-service.outputs.changes != '' }}
        working-directory: TweetService
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kwetter:tweet-service:latest .
      
      - name: Push to Docker Hub
        if: ${{ steps.check-tweet-service.outputs.changes != '' }}
        uses: docker/build-push-action@v2
        with:
          context: TweetService
          file: TweetService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:tweet-service:latest
          
  trend-service:
    environment: TrendService
    name: Build TrendService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go env
        uses: actions/setup-go@v3
        with: 
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
 
      - name: Check for changes in TrendService
        id: check-trend-service
        run: |
          git fetch
          changed_files=$(git diff --name-only origin/main -- TrendService/)
          echo "::set-output name=changes::${changed_files}"
      
      - name: Build Trend Service
        if: ${{ steps.check-trend-service.outputs.changes != '' }}
        working-directory: TrendService
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kwetter:trend-service:latest .
      
      - name: Push to Docker Hub
        if: ${{ steps.check-trend-service.outputs.changes != '' }}
        uses: docker/build-push-action@v2
        with:
          context: TrendService
          file: TrendService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:trend-service:latest
          
  account-service:
    environment: AccountService
    name: Build AccountService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go env
        uses: actions/setup-go@v3
        with: 
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
 
      - name: Check for changes in AccountService
        id: check-account-service
        run: |
          git fetch
          changed_files=$(git diff --name-only origin/main -- AccountService/)
          echo "::set-output name=changes::${changed_files}"
      
      - name: Build Account Service
        if: ${{ steps.check-account-service.outputs.changes != '' }}
        working-directory: AccountService
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kwetter:account-service:latest .
      
      - name: Push to Docker Hub
        if: ${{ steps.check-account-service.outputs.changes != '' }}
        uses: docker/build-push-action@v2
        with:
          context: AccountService
          file: AccountService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:account-service:latest
  
  gateway-service:
    environment: KwetterGateway
    name: Build KwetterGateway
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go env
        uses: actions/setup-go@v3
        with: 
          go-version: 1.20
 
      - name: Check for changes in KwetterGateway
        id: check-gateway-service
        run: |
          git fetch
          changed_files=$(git diff --name-only origin/main -- KwetterGateway/)
          echo "::set-output name=changes::${changed_files}"
      
      - name: Build KwetterGateway
        if: ${{ steps.check-gateway-service.outputs.changes != '' }}
        working-directory: KwetterGateway
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kwetter:gateway-service:latest .
      
      - name: Push to Docker Hub
        if: ${{ steps.check-gateway-service.outputs.changes != '' }}
        uses: docker/build-push-action@v2
        with:
          context: KwetterGateway
          file: KwetterGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:gateway-service:latest
  
  auth-service:
    environment: AuthService
    name: Build AuthService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go env
        uses: actions/setup-go@v3
        with: 
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
 
      - name: Check for changes in AuthService
        id: check-auth-service
        run: |
          git fetch
          changed_files=$(git diff --name-only origin/main -- AuthService/)
          echo "::set-output name=changes::${changed_files}"
      
      - name: Build Auth Service
        if: ${{ steps.check-auth-service.outputs.changes != '' }}
        working-directory: AuthService
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/kwetter:auth-service:latest .
      
      - name: Push to Docker Hub
        if: ${{ steps.check-auth-service.outputs.changes != '' }}
        uses: docker/build-push-action@v2
        with:
          context: AuthService
          file: AuthService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:auth-service:latest
