name: Go
on:
  push:
    branches: [ "main" ]
    paths:
      - KwetterGateway/**
      - AccountService/**
      - AuthService/**
      - TweetService/**
      - TrendService/**

env:
  ACTIONS_STEP_DEBUG: true
jobs:
  tweet-service:
    if: ${{ github.event_name == 'push' && contains(github.event.paths, 'TweetService/**') }}
    environment: TweetService
    name: Build TweetService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

      - name: Build Tweet Service
        working-directory: TweetService
        run: docker build . -t tweet-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: TweetService
          file: TweetService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:tweet-service-latest

  trend-service:
    if: ${{ github.event_name == 'push' && contains(github.event.paths, 'TrendService/**') }}
    environment: TrendService
    name: Build TrendService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: TrendService
          file: TrendService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:trend-service-latest

  account-service:
    if: ${{ github.event_name == 'push' && contains(github.event.paths, 'AccountService/**') }}
    environment: AccountService
    name: Build AccountService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

      - name: Build Account Service
        working-directory: AccountService
        run: docker build . -t account-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: AccountService
          file: AccountService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:account-service-latest

  gateway-service:
    if: ${{ github.event_name == 'push' && contains(github.event.paths, 'KwetterGateway/**') }}
    environment: KwetterGateway
    name: Build KwetterGateway
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Build KwetterGateway
        working-directory: KwetterGateway
        run: docker build . -t gateway-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: KwetterGateway
          file: KwetterGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:gateway-service-latest

  auth-service:
    if: ${{ github.event_name == 'push' && contains(github.event.paths, 'AuthService/**') }}
    environment: AuthService
    name: Build AuthService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Build Auth Service
        working-directory: AuthService
        run: docker build . -t auth-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: AuthService
          file: AuthService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:auth-service-latest
