name: Deploy AuthService
on:
  push:
    branches: [ "main" ]
    paths:
      - AuthService/**
jobs:
  auth-service:
    environment: AuthService
    name: Build AuthService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
        env:
          MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}

      - name: Build Auth Service
        working-directory: AuthService
        run: docker build . -t auth-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: AuthService
          file: AuthService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:auth-service-latest
  
