name: Deploy Gateway
on:
  push:
    branches: [ "main" ]
    paths:
      - KwetterGateway/**
      
jobs:
  gateway-service:
    environment: KwetterGateway
    name: Build KwetterGateway
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - name: Run Tests
        working-directory: KwetterGateway
        run: go test ./...

      - name: Build KwetterGateway
        working-directory: KwetterGateway
        run: docker build . -t gateway-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: KwetterGateway
          file: KwetterGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:gateway-service-latest
