name: Deploy AuthService
on:
  push:
    branches: [ "main" ]
    paths:
      - AuthService/**
jobs:
  auth-service:
    environment: AuthService
    name: Build AuthService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Create .env file
        run: |
          cd AuthService
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" > .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "RMQ_KEY"=${{ secrets.RMQ_KEY }} >> .env

      - name: Run Tests
        working-directory: AuthService
        run: go test ./...

      - name: Build Auth Service
        working-directory: AuthService
        run: docker build . -t auth-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: AuthService
          file: AuthService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:auth-service-latest
  
