name: Deploy AccountService
on:
  push:
    branches: [ "main" ]
    paths:
      - AccountService/**
  workflow_dispatch:

jobs:
  account-service:
    environment: AccountService
    name: Build AccountService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - name: Create .env file
        run: | 
          cd AccountService
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" > .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "RMQ_KEY"=${{ secrets.RMQ_KEY }} >> .env

      - name: Build Account Service
        working-directory: AccountService
        run: docker build . -t account-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: AccountService
          file: AccountService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:account-service-latest
          
      - name: Deploy to Cloud
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group Kwetter --name KwetterCluster
          kubectl delete deployment accountservice-deployment
          kubectl apply -f https://raw.githubusercontent.com/Portfolio-Adv-Software/Kwetter/main/KwetterCluster/AccountService/deployment.yaml
          
          
