name: Deploy TweetService
on:
  push:
    branches: [ "main" ]
    paths:
      - TweetService/**
  workflow_dispatch:

jobs:
  tweet-service:
    environment: TweetService
    name: Build TweetService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - name: Create .env file
        run: |
          cd TweetService
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" > .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "RMQ_KEY"=${{ secrets.RMQ_KEY }} >> .env

      - name: Build Tweet Service
        working-directory: TweetService
        run: docker build . -t tweet-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: TweetService
          file: TweetService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:tweet-service-latest
