name: Deploy Gateway
on:
  push:
    branches: [ "main" ]
    paths:
      - KwetterGateway/**
  workflow_dispatch:

jobs:
  gateway-service:
    environment: KwetterGateway
    name: Build KwetterGateway
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.0

      - name: Run Tests
        working-directory: KwetterGateway
        run: go test ./internal/Tests/...

      - name: Build KwetterGateway
        working-directory: KwetterGateway
        run: docker build . -t gateway-service-latest

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: KwetterGateway
          file: KwetterGateway/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:gateway-service-latest
          
      - name: Deploy to Cloud
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group Kwetter --name KwetterCluster
          kubectl delete deployment gatewayservice-deployment
          kubectl apply -f https://raw.githubusercontent.com/Portfolio-Adv-Software/Kwetter/main/KwetterCluster/GatewayService/deployment.yaml
