name: Deploy TrendService
on:
  push:
    branches: [ "main" ]
    paths:
      - TrendService/**
jobs:
  trend-service:
    environment: TrendService
    name: Build TrendService
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go env
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Create .env file
        run: |
          cd TrendService
          echo "MONGO_USERNAME=${{ secrets.MONGO_USERNAME }}" > .env
          echo "MONGO_PASSWORD=${{ secrets.MONGO_PASSWORD }}" >> .env
          echo "RMQ_KEY"=${{ secrets.RMQ_KEY }} >> .env

      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: TrendService
          file: TrendService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kwetter:trend-service-latest
